# Form implementation generated from reading ui file 'd:\Programmieren\Python\Padel_Tournament\src\padel_tournament\ui\designer\pages\main_window.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TournamentApp(object):
    def setupUi(self, TournamentApp):
        TournamentApp.setObjectName("TournamentApp")
        TournamentApp.resize(980, 720)
        self.centralwidget = QtWidgets.QWidget(parent=TournamentApp)
        self.centralwidget.setObjectName("centralwidget")
        self.centralLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.centralLayout.setObjectName("centralLayout")
        self.stack = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stack.setObjectName("stack")
        self.centralLayout.addWidget(self.stack)
        TournamentApp.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=TournamentApp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 980, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(parent=self.menubar)
        self.menuView.setObjectName("menuView")
        TournamentApp.setMenuBar(self.menubar)
        self.save_action = QtGui.QAction(parent=TournamentApp)
        self.save_action.setObjectName("save_action")
        self.load_action = QtGui.QAction(parent=TournamentApp)
        self.load_action.setObjectName("load_action")
        self.csv_action = QtGui.QAction(parent=TournamentApp)
        self.csv_action.setObjectName("csv_action")
        self.pdf_action = QtGui.QAction(parent=TournamentApp)
        self.pdf_action.setObjectName("pdf_action")
        self.exit_action = QtGui.QAction(parent=TournamentApp)
        self.exit_action.setObjectName("exit_action")
        self.theme_action = QtGui.QAction(parent=TournamentApp)
        self.theme_action.setCheckable(True)
        self.theme_action.setObjectName("theme_action")
        self.auto_action = QtGui.QAction(parent=TournamentApp)
        self.auto_action.setCheckable(True)
        self.auto_action.setChecked(True)
        self.auto_action.setObjectName("auto_action")
        self.menuFile.addAction(self.save_action)
        self.menuFile.addAction(self.load_action)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.csv_action)
        self.menuFile.addAction(self.pdf_action)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.exit_action)
        self.menuView.addAction(self.theme_action)
        self.menuView.addAction(self.auto_action)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(TournamentApp)
        self.stack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TournamentApp)

    def retranslateUi(self, TournamentApp):
        _translate = QtCore.QCoreApplication.translate
        TournamentApp.setWindowTitle(_translate("TournamentApp", "Padel Tournament Manager"))
        self.menuFile.setTitle(_translate("TournamentApp", "File"))
        self.menuView.setTitle(_translate("TournamentApp", "View"))
        self.save_action.setText(_translate("TournamentApp", "Save…"))
        self.load_action.setText(_translate("TournamentApp", "Load…"))
        self.csv_action.setText(_translate("TournamentApp", "Export CSV…"))
        self.pdf_action.setText(_translate("TournamentApp", "Export PDF…"))
        self.exit_action.setText(_translate("TournamentApp", "Exit"))
        self.theme_action.setText(_translate("TournamentApp", "Dark mode"))
        self.auto_action.setText(_translate("TournamentApp", "Auto-update rankings"))
