# Form implementation generated from reading ui file 'd:\Programmieren\Python\Padel_Tournament\src\padel_tournament\ui\designer\pages\names_page\names_page.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NamesPage(object):
    def setupUi(self, NamesPage):
        NamesPage.setObjectName("NamesPage")
        NamesPage.resize(640, 480)
        self.mainLayout = QtWidgets.QVBoxLayout(NamesPage)
        self.mainLayout.setSpacing(16)
        self.mainLayout.setObjectName("mainLayout")
        self.title_label = QtWidgets.QLabel(parent=NamesPage)
        self.title_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.mainLayout.addWidget(self.title_label)
        self.names_scroll = QtWidgets.QScrollArea(parent=NamesPage)
        self.names_scroll.setWidgetResizable(True)
        self.names_scroll.setObjectName("names_scroll")
        self.names_container = QtWidgets.QWidget()
        self.names_container.setObjectName("names_container")
        self.names_layout = QtWidgets.QVBoxLayout(self.names_container)
        self.names_layout.setSpacing(8)
        self.names_layout.setObjectName("names_layout")
        self.names_scroll.setWidget(self.names_container)
        self.mainLayout.addWidget(self.names_scroll)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setSpacing(4)
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonLayout.addItem(spacerItem)
        self.generate_button = QtWidgets.QPushButton(parent=NamesPage)
        self.generate_button.setMinimumSize(QtCore.QSize(140, 0))
        self.generate_button.setMaximumSize(QtCore.QSize(140, 16777215))
        self.generate_button.setObjectName("generate_button")
        self.buttonLayout.addWidget(self.generate_button)
        self.fill_button = QtWidgets.QPushButton(parent=NamesPage)
        self.fill_button.setMinimumSize(QtCore.QSize(140, 0))
        self.fill_button.setMaximumSize(QtCore.QSize(140, 16777215))
        self.fill_button.setObjectName("fill_button")
        self.buttonLayout.addWidget(self.fill_button)
        self.back_button = QtWidgets.QPushButton(parent=NamesPage)
        self.back_button.setMinimumSize(QtCore.QSize(140, 0))
        self.back_button.setMaximumSize(QtCore.QSize(140, 16777215))
        self.back_button.setObjectName("back_button")
        self.buttonLayout.addWidget(self.back_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonLayout.addItem(spacerItem1)
        self.mainLayout.addLayout(self.buttonLayout)

        self.retranslateUi(NamesPage)
        QtCore.QMetaObject.connectSlotsByName(NamesPage)

    def retranslateUi(self, NamesPage):
        _translate = QtCore.QCoreApplication.translate
        self.title_label.setText(_translate("NamesPage", "Enter Player Names"))
        self.generate_button.setText(_translate("NamesPage", "Next"))
        self.fill_button.setText(_translate("NamesPage", "Generic Names"))
        self.back_button.setText(_translate("NamesPage", "Back"))
